name: chokchey_finance
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.25+43
# version: 1.2.12+22

environment:
  sdk: '>=3.1.2 <4.0.0'
  # sdk: ">=2.13.4 <3.0.0"

dependencies:
  gap: ^3.0.1
  pinput: ^3.0.1
  easy_stepper: ^0.8.3
  dropdown_button2: ^2.3.9
  autocomplete_textfield: ^2.0.1
  awesome_dialog: ^3.0.2
  getwidget: ^4.0.0
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.5
  dio: ^5.0.2
  syncfusion_flutter_pdfviewer: ^23.2.7
  dropdown_search: ^5.0.6
  expandable: ^5.0.1
  file: ^6.1.4
  file_picker: ^5.2.6
  firebase_auth: ^4.4.0
  firebase_core: ^2.14.0
  firebase_database: ^10.1.0
  firebase_messaging: ^14.6.4
  firebase_analytics: ^10.4.3
#  location: ^5.0.3
  flutter:
    sdk: flutter
  flutter_chips_input: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_form_builder: ^9.0.0
  flutter_localization: ^0.1.12
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.1.0
  geocoding: ^2.1.0
  get: ^4.6.5
  group_list_view: ^1.1.1
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  logger: ^2.0.2
  flutter_pdfview: ^1.3.2
  date_picker_plus: ^1.1.4
  geolocator: ^10.1.0
  multi_select_flutter: ^4.1.3
  package_info: ^2.0.0
  path_provider: ^2.0.13
  permission_handler: ^11.0.0
  photo_view: ^0.14.0
  platform: ^3.1.0
  provider: ^6.0.5
  select_dialog: ^2.0.0
  slide_popup_dialog_null_safety: ^1.0.0
  sticky_headers: ^0.3.0+2
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.7
  shared_preferences: ^2.0.18
  # upgrader: ^6.2.0
  flutter_svg: ^2.0.4
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3
  flutter_swiper_plus: ^2.0.4
  form_builder_validators: ^9.0.0
  pdf: ^3.10.1
  secure_application: ^3.8.0
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.0.4
  sqflite: ^2.2.7
  modal_bottom_sheet: ^3.0.0-pre
  # intl: ^0.17.0
  font_awesome_flutter: ^10.4.0
  screen_protector: ^1.2.0
  encrypt: ^5.0.1
  fdottedline_nullsafety: ^2.0.1
  flutter_inappwebview: ^5.7.2+3
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  google_maps_flutter: ^2.2.8
  shimmer: ^3.0.0
  syncfusion_flutter_pdf: ^23.1.36
  open_file: ^3.3.2
  community_charts_flutter: ^1.0.1
  new_version_plus: ^0.0.10
  in_app_update: ^4.1.4
  flutter_local_notifications: ^15.1.0+1
  syncfusion_flutter_core: ^23.2.7
  animated_text_kit: ^4.2.2
  page_transition: ^2.1.0

dev_dependencies:

  # flutter_launcher_icons: "^0.9.2"
  retrofit_generator: ^7.0.8
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter
  # retrofit_generator: ^5.0.0
  # json_serializable: ^4.4.0
# flutter_icons:
  # android: true
  # ios: true
  # image_path: "assets/images/app_icon/1024.png"
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/images/app_icon/1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/svg/.
    - assets/images/.
    - lang/en.json
    - lang/km.json
    - assets/pdf/
    - assets/images/list.png
    - assets/images/percentage.png
    - assets/pdf/requirementchecklist.pdf
    - assets/pdf/oraccccccc.pdf

    - assets/images/101.png
    - assets/images/102.png
    - assets/images/103.png
    - assets/images/104.png

    - assets/images/211.png
    - assets/images/212.png
    - assets/images/213.png
    - assets/images/214.png
    - assets/images/215.png
    - assets/images/216.png

    - assets/images/221.png
    - assets/images/222.png
    - assets/images/223.png
    - assets/images/224.png
    - assets/images/225.png
    - assets/images/226.png
    - assets/images/227.png
    - assets/images/228.png
    - assets/images/chokchey-logo.png
    - assets/up-coming.png

    - assets/images/301.png
    - assets/images/302.png
    - assets/images/english.png
    - assets/images/khmer.png
    - assets/images/phonecall.png
    - assets/Credit_Operation_Manual.pdf
    - assets/images/khm.png
    - assets/ca/lets-encrypt-r3.pem
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: sf_pro_display
      fonts:
        - asset: assets/fonts/sf_pro_display.ttf
    - family: roboto_regular
      fonts:
        - asset: assets/fonts/roboto-regular.ttf
    - family: nokora_regular
      fonts:
        - asset: assets/fonts/nokora-regular.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
